# -*- coding: utf-8 -*-
"""hw2_p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ad6jQltyT40Fdf6cXx55Dq1GOxrruAXF
"""

import csv
import numpy as np

arr = []
with open('faces.csv', 'r') as f:
    spamreader = csv.reader(f, delimiter=' ')
    for row in f:
        arr.append([float(x) for x in row.split(',')])
arr = np.array(arr)

def pca(data):

    sigma = np.matmul(data.T, data) / data.shape[0]
    eigval, eigvec = np.linalg.eigh(sigma)
    # sort eigen-vectors/values in decenting order
    idx = np.argsort(eigval)[::-1]
    eigvec = eigvec[:,idx]
    eigval = eigval[idx]
    # select top n dim
    # topn_eigvec = eigvec[:,:dim]
    # topn_eigval = eigval[:dim]
    return eigvec, eigval

eigvec, eigval = pca(arr)

key_idx = [1, 2, 10, 30, 50]
for idx in key_idx:
    print('Eigenvalues ({}={}): {}'.format('lambda', idx, eigval[idx-1]))

fractional_err = []
eigval_sum = sum(eigval)
topn_sum = 0
for idx, val in enumerate(eigval):
    topn_sum += val
    fractional_err.append(1-(topn_sum/eigval_sum))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
matplotlib.rcParams['figure.dpi']= 150


plt.figure()
plt.plot(list(range(1,51)), np.array(fractional_err[:50]), c='red')
plt.xlabel(r'$k$')
plt.ylabel('Error')
plt.title('Fractional Construction Error')

plt.subplots()
for idx in range(10):
    plt.subplot(1,10,idx+1)
    plt.imshow(np.reshape((eigvec.T)[idx], (84, 96)).T, cmap='gray')
    plt.axis('off')

img_ids = [0, 23, 64, 67, 256]
# img_ids = [0]
ks = [1, 2, 5, 10, 50]

plt.subplots()
for i, img_id in enumerate(img_ids):
    
    plt.subplot(5,6,i*6+1)
    plt.imshow(np.reshape(arr[img_id], (84,96)).T, vmin=0, vmax=1, cmap='gray')
    plt.axis('off')

    for j, k in enumerate(ks):

        reconstruct = np.matmul(arr[img_id], np.matmul(eigvec[:,:k],eigvec[:,:k].T))

        plt.subplot(5,6,i*6+j+2)
        plt.imshow(np.reshape(reconstruct, (84,96)).T, vmin=0, vmax=1, cmap='gray')
        plt.axis('off')